### ISSUE TITLE
nixops deploy --check --allow-recreate doesn't update the machine's metadata

### ISSUE THREAD

**Issue by grahamc** [input-output-hk/nixops-packet#19]
This means creating a new machine after it has been destroyed upstream will try to deploy the old machine's config, including IP addresses, partition IDs, and disk layout. After this recreation, it is important to sync the metadata from the machine back in to the database.

This should probably also work  even when deploying with `--dry-activate`, since that is usually when I end up recreating machines.

**Comment by johnalotoski** [comment]
Fixed in https://github.com/input-output-hk/nixops-packet/commit/e9e37e3d71aed584f46fecb2b631173a567e8249 and prior commits.

* `--allow-recreate` is now required on deploys which existed (or were registered to state) and have gone missing
* Works with `--dry-activate` (at least on testing with c2.medium.x86)
* New metadata and provision system file are pulled into state after re-creating
* Old metadata and provisioning file are kept in nixops state until `--allow-recreate` deploy is performed to allow for inspection

**Comment by johnalotoski** [comment]
Closing.  Re-open this ticket or create a new ticket if the issue persists.
