### ISSUE TITLE
Spot machines which disappear don't get pruned

### ISSUE THREAD

**Issue by grahamc** [input-output-hk/nixops-packet#7]
One of my deployments uses spot machines. The machine was reaped from under me, but nixops never realized it. I had to manually delete it from the network with `nixops delete-resources`.

**Comment by johnalotoski** [comment]
Fixed in https://github.com/input-output-hk/nixops-packet/commit/e9e37e3d71aed584f46fecb2b631173a567e8249.

* There is now an instance API health check at the start of a wait_for_ssh_nixops_packet function call and every 60 seconds after.
* A spot instance that goes missing will be recognized during a deploy.  Either deploy with `--allow-recreate` to re-spawn or `destroy` or `delete-resources` to purge it from state if it's no longer wanted.

**Comment by johnalotoski** [comment]
Closing.  Re-open this ticket or create a new ticket if the issue persists.
